### ISSUE TITLE
watir-screenshot-stitch requires ruby >= 2.3.x

### ISSUE THREAD

**Issue by rbojjasba** [samnissen/watir-screenshot-stitch#21]
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': /Library/Ruby/Gems/2.0.0/gems/watir-screenshot-stitch-0.6.5/lib/watir-screenshot-stitch.rb:81: syntax error, unexpected '.' (SyntaxError)
        return false unless @browser&.name == :firefox
                                      ^
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from stitich.rb:3:in `<main>'

**Comment by samnissen** [comment]
Thanks for submitting, @rbojjasba. 

`@browser&.name` is an example of [the safe navigator operator](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), which lets you call a method on an object that might not implement it and return nil in that case, rather than raise an error. As you can read in the link, it was introduced in Ruby 2.3.

#### 2.0.0
```ruby
@browser = nil
@browser&.name
# => SyntaxError: (irb):2: syntax error, unexpected '.'
```

#### 2.4.1
```
@browser = nil
@browser&.name == :firefox
# => false
```

I'll leave this issue open. If you'd like to solve it by adding support for earlier versions of Ruby with a pull request, please fire away. Otherwise, I will likely indicate that Ruby 2.3+ is required and call it solved.

**Comment by homeadd2** [comment]
went to ruby 2.3.3, but now having this issues 
```
rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:208:in `rescue in validate!': ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)
	from /Users/ravibojja/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:206:in `validate!'
	from /Users/ravibojja/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:118:in `block in create'
	from /Users/ravibojja/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:117:in `tap'
	from /Users/ravibojja/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:117:in `create'
	from /Users/ravibojja/.rvm/gems/ruby-2.3.3/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:34:in `read'
	from /Users/ravibojja/Downloads/watir-screenshot-stitch-master/lib/watir-screenshot-stitch.rb:84:in `bug_shot?'
	from /Users/ravibojja/Downloads/watir-screenshot-stitch-master/lib/watir-screenshot-stitch.rb:60:in `base64_canvas'
	from /Users/ravibojja/Downloads/watir-screenshot-stitch-master/stitich.rb:14:in `<top (required)>'
	from -e:1:in `load'``
```

**Comment by rbojjasba** [comment]
like to give 5 stars, cool util, 
Users, please remove gem 'watir' in your env.rb , might cause internal Wait Watir as browser is also initialized through watir-screenshot-stitch gem

**Comment by samnissen** [comment]
@rbojjasba can you clarify further what issue you had under what circumstances? I’d like to document any potential dependency.
