### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by sandeepnagra** [samnissen/watir-screenshot-stitch#23]
I get following error while installing due to a dependency failure. I tried to install on ruby 2.4.1 and ruby 2.4.0 both

An error occurred while installing debug_inspector (0.0.3), and Bundler cannot
continue.
Make sure that `gem install debug_inspector -v '0.0.3'` succeeds before
bundling.

**Comment by samnissen** [comment]
What happens when you try installing that gem version? Can you post the backtrace?

**Comment by sandeepnagra** [comment]
```
$ gem install watir-screenshot-stitch
Building native extensions.  This could take a while...
ERROR:  Error installing watir-screenshot-stitch:
        ERROR: Failed to build gem native extension.

    current directory: /Users/xyz/.rvm/gems/ruby-2.4.1/gems/debug_inspector-0.0.3/ext/debug_inspector
/Users/xyz/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20180320-69481-1sv6hbb.rb extconf.rb
creating Makefile

current directory: /Users/xyz/.rvm/gems/ruby-2.4.1/gems/debug_inspector-0.0.3/ext/debug_inspector
make "DESTDIR=" clean
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

current directory: /Users/xyz/.rvm/gems/ruby-2.4.1/gems/debug_inspector-0.0.3/ext/debug_inspector
make "DESTDIR="
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

make failed, exit code 1

Gem files will remain installed in /Users/xyz/.rvm/gems/ruby-2.4.1/gems/debug_inspector-0.0.3 for inspection.
Results logged to /Users/xyz/.rvm/gems/ruby-2.4.1/extensions/x86_64-darwin-15/2.4.0/debug_inspector-0.0.3/gem_make.out
```

**Comment by samnissen** [comment]
Thanks for the update. This has something to do with your Ruby environment. I'm fairly sure you need to [install or update Xcode tools](https://apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path), based on a cursory search. 

Either way, nothing specific to the gem. Good luck

**Comment by sandeepnagra** [comment]
Damn High Sierra! Fixed that one with the command `xcode-select --install` and now the gem is installed. I then ran a small test:

```
require 'watir-screenshot-stitch'

path = "full-page-image.png"
opts = { :page_height_limit => 15000 }

b = Watir::Browser.new :chrome
b.goto "https://en.wikipedia.org/wiki/Shaitan_Singh"
b.screenshot.save_stitch(path, b, opts)
```

It fails with following error:

```
/Users/mm57710/.rvm/gems/ruby-2.4.1/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:208:in `rescue in validate!': ImageMagick/GraphicsMagick is not installed (MiniMagick::Invalid)
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:206:in `validate!'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:118:in `block in create'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:117:in `tap'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:117:in `create'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/mini_magick-4.8.0/lib/mini_magick/image.rb:34:in `read'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/watir-screenshot-stitch-0.6.0/lib/watir-screenshot-stitch.rb:92:in `calculate_dimensions'
	from /Users/mm57710/.rvm/gems/ruby-2.4.1/gems/watir-screenshot-stitch-0.6.0/lib/watir-screenshot-stitch.rb:31:in `save_stitch'
	from /Users/mm57710/RubymineProjects/test/full_page_screenshots.rb:39:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

I was assuming the dependencies will be installed automatically but I guess one of them is missing. I will install that and retry.

**Comment by sandeepnagra** [comment]
Ok, It seems like I only need to install GraphicsMagick  using command `brew install graphicsmagick` and I don't need a separate gem like 'graphicsmagick'

It works with that but the image has white space gaps.
![full-page-image](https://user-images.githubusercontent.com/9598669/37720506-c70d70ec-2cfd-11e8-9bca-df86ae4a6609.png)

 I will try with ImageMagick too.

**Comment by sandeepnagra** [comment]
I have same result with ImageMagick too. Is that how it is suppose to work? Just curious.

Also, it would be great if under the requirements you can mention that it needs ImageMagick / GraphicsMagick to be pre-installed and maybe add the brew install commands there. It will be helpful.

**Comment by sandeepnagra** [comment]
I will report a separate improvement for the white space issue.

**Comment by samnissen** [comment]
@sandeepnagra Glad you were able to get along further with it.

The README does mention the reliance on ImageMagick:

> ### MiniMagick
> watir-screenshot-stitch relies on [MiniMagick](https://github.com/minimagick/minimagick) (and thus ImageMagick). You might need to review that gem's requirements and installation before proceeding.

I'm sure the README could be clearer or more verbose, which you're welcome to submit a PR to improve!

Ideally, MiniMagick would install ImageMagick. I do not feel technically equipped to tackle that problem, but if you do, I suggest you work with that gem's maintainers.

I'll reply to your separate ticket on the whitespace issue.
