### ISSUE TITLE
base64_canvas screenshots doesn't include cross domain images

### ISSUE THREAD

**Issue by sandeepnagra** [samnissen/watir-screenshot-stitch#28]
I have a fix for it but it works in all browsers except Firefox and IE.

Chrome, Edge, Safari works like a charm. The fix is in my fork for your review @samnissen  - https://github.com/sandeepnagra/watir-screenshot-stitch/blob/master/lib/watir-screenshot-stitch.rb

All I did is upgrade the html2canvas.js file and replace a deprecated option **onrendered** with new **.then** option.

I am trying to find a fix for Firefox & IE as well but I haven't had any good luck with it yet. Will keep searching and if I find a fix for those two browsers, I will add it and then raise a PR.

**Comment by samnissen** [comment]
I implemented code to switch between the latest htmlcanvas with onrendered and and the current version with the current JavaScript, and the screenshots I took of Mass Mutual's site are identical. Do you have any other sites that exhibit this behavior that I can test this against?

**Comment by sandeepnagra** [comment]
@samnissen - when you say identical, do you mean you still don't see images included? If yes, then look at my PR and update the javascript to what I have in my PR and it should work.

**Comment by samnissen** [comment]
Sorry, I mean that the following all look effectively the same:
- `base64_canvas` screenshot of massmutual.com using the current / old method with Firefox
- `base64_canvas` screenshot of massmutual.com using the current / old method with Chrome
- `base64_canvas` screenshot of massmutual.com using the new / proposed method with Chrome

I cannot replicate the image you showed once (I can't remember where) of mass Mutual's website with many of the images looking wrong or missing.

**Comment by samnissen** [comment]
Well, many thanks for looking into this anyway. Let me know if you can re-reproduce the bug conditions, and I'll reopen this straight away.

**Comment by sandeepnagra** [comment]
Hi @samnissen,

I found the scenario for which this issue is reproducible. Try taking a base64_canvas screenshot of this site - https://advisors.massmutual.com/

It will generate a bad/corrupt PNG. Now try the same with the changes I have made in my PR - https://github.com/sandeepnagra/watir-screenshot-stitch and it will render a proper PNG.

**Comment by samnissen** [comment]
Fixed by #36
