### ISSUE TITLE
Warning over rubyzip versioning requires change to gemspec

### ISSUE THREAD

**Issue by samnissen** [samnissen/watir-screenshot-stitch#44]
I get this warning when building the gem:

```ruby
WARNING:  pessimistic dependency on rubyzip (~> 1.2.2) may be overly strict
  if rubyzip is semantically versioned, use:
    add_runtime_dependency 'rubyzip', '~> 1.2', '>= 1.2.2'
```

Please check if rubyzip is appropriately versioned and, if so, make this change to the gemspec.

**Comment by tenpaiyomi** [comment]
I'll grab this issue!

**Comment by tenpaiyomi** [comment]
Here you go @samnissen.  Let me know if there are any other changes requested.
