### ISSUE TITLE
html2canvas is not working for Chrome

### ISSUE THREAD

**Issue by Rajagopalan-M** [samnissen/watir-screenshot-stitch#59]
Your gem perfectly works for Firefox and also works in Chrome for the url `https://github.com/mozilla/geckodriver/issues/570` but for my url `https://uat.allianz-go.com/login.max?preprocess=true` it only works for Firefox but it's not working for Chrome

```
require 'watir-screenshot-stitch'

b = Watir::Browser.new
b.goto "https://uat.allianz-go.com/login.max?preprocess=true"

png = b.screenshot.base64_canvas
path = "Pic.png"
File.open(path, 'wb') { |f| f.write(Base64.decode64(png)) }
```

It throws the following error

```
Traceback (most recent call last):
        38: from C:/A/RubyAutomation/AppData/Example.rb:6:in `<main>'
        37: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/watir-screenshot-stitch-0.7.4/lib/watir-screenshot-stitch.rb:92:in `base64_canvas'
        36: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/watir-6.16.5/lib/watir/browser.rb:221:in `execute_script'
        35: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:213:in `execute_script'
        34: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:305:in `execute_script'
        33: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:567:in `execute'
        32: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/bridge.rb:167:in `execute'
        31: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
        30: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/default.rb:114:in `request'
        29: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `create_response'
        28: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/http/common.rb:88:in `new'
        27: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:34:in `initialize'
        26: from C:/Ruby26/lib/ruby/gems/2.6.0/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/response.rb:72:in `assert_ok'
        25: from        RtlGetAppContainerNamedObjectPath [0x77CA7BF4+180]
        24: from        RtlGetAppContainerNamedObjectPath [0x77CA7C24+228]
        23: from        BaseThreadInitThunk [0x75526359+25]
        22: from        Ordinal0 [0x00FA4984+2181508]
        21: from        Ordinal0 [0x00F923D1+2106321]
        20: from        Ordinal0 [0x00F922AB+2106027]
        19: from        Ordinal0 [0x00F87F11+2064145]
        18: from        GetHandleVerifier [0x011FBCA8+1398376]
        17: from        GetHandleVerifier [0x012070E6+1444518]
        16: from        GetHandleVerifier [0x011FB399+1396057]
        15: from        GetHandleVerifier [0x011FB71A+1396954]
        14: from        Ordinal0 [0x00F90C99+2100377]
        13: from        Ordinal0 [0x00DA3DC9+81353]
        12: from        Ordinal0 [0x00DA3E3E+81470]
        11: from        Ordinal0 [0x00DA2E77+77431]
        10: from        Ordinal0 [0x00DBEB0B+191243]
         9: from        Ordinal0 [0x00DC8773+231283]
         8: from        Ordinal0 [0x00DBEC5D+191581]
         7: from        Ordinal0 [0x00DC8F4C+233292]
         6: from        Ordinal0 [0x00E1D64D+579149]
         5: from        Ordinal0 [0x00E1CF73+577395]
         4: from        Ordinal0 [0x00E1D06E+577646]
         3: from        Ordinal0 [0x00E1AEC8+569032]
         2: from        Ordinal0 [0x00F7A131+2007345]
         1: from        Ordinal0 [0x0108D343+3134275]
Backtrace:: javascript error: html2canvas is not defined (Selenium::WebDriver::Error::JavascriptError)
  (Session info: chrome=85.0.4183.83)

```

**Comment by samnissen** [comment]
@Rajagopalan-M Sorry to hear this isn't working for you. Unfortunately, that URL is not available to me (I'm guessing it is on a private network?), and I can't reproduce your error when I instead visit other URLs, like allianz.com, for instance. Also, I cannot test from a Windows environment. 

Are you able to directly employ html2canvas on the site manually in the same environment? Alternatively, are you able to use the `save_stitch` function instead?

**Comment by Rajagopalan-M** [comment]
@samnissen 
Hi, I did not know what I did that day, but it works so perfectly, Thanks. But when my automation moves, it colours the fields whichever gets filled, but your screenshot is not having that colour in its screenshots. Is it a bug?

**Comment by samnissen** [comment]
I assume you are referring to the `base64_canvas` method? This method is dependent on the performance of the html2canvas javascript package. As this still hasn't released a 1.0, it will definitely have some rough edges. (I found whole elements not being captured in my testing.) For each browser, I found better performance for different packages, but haven't tested this in some time. Also, new browser versions could change the performance of the canvas element. Also, as mentioned, I have not tested performance on Windows, which could also affect performance. 

Between the various possible permutations that might affect the performance and the beta nature of html2canvas, I cannot recommend strongly enough seeing if the `save_stitch` function can work for you. Even better -- if you can use Firefox, `base64_geckodriver` has flawless performance in my testing. 

If those do not work for you, I suggest you take a look at [how we implement the html2canvas method](https://github.com/samnissen/watir-screenshot-stitch/blob/master/lib/watir-screenshot-stitch.rb#L91:L100), and manually recreate it with different [html2canvas release versions](https://github.com/niklasvh/html2canvas/releases) to see if any improve performance -- if you can let me know what you find, we might be able to update the gem based on that.

**Comment by Rajagopalan-M** [comment]
Hey no no! I am not using html2canvas method. As you per your suggestion, I started using this `save_stitch`, It's working perfectly for chrome, but it's not capturing the colour. I am giving the colour for the filed after they fill(text_field) the text or after the selection(select_list), but that colour is not captured in your screenshot. Could it be a bug?

**Comment by samnissen** [comment]
Interesting. A theme with this gem is: It is effectively a wrapper around other technologies. So, `save_stitch` is three things: 

1. take a non-fullpage screenshot with the browser default screenshot tech
2. scroll down using Selenium and JavaScript, and repeat step 1
3. combine all of the screenshots using MiniMagick

This is another example where I suspect the issue is probably outside the gem -- maybe with the browser default screenshot tech -- but could be lots of things. If you can provide a script that replicates it, I can test more. Maybe post the script into a new issue?

**Comment by Rajagopalan-M** [comment]
Hi, Thanks for reply. No, I think that's not the case, when I normally take the screenshot, it is having the colour. You could see here

![image](https://user-images.githubusercontent.com/31696622/93883860-c3334a80-fcff-11ea-9aa7-d5814bb5b109.png)

**Comment by sandeepnagra** [comment]
> Hi, Thanks for reply. No, I think that's not the case, when I normally take the screenshot, it is having the colour. You could see here(workers Comp)
> 
> ![image](https://user-images.githubusercontent.com/31696622/93883860-c3334a80-fcff-11ea-9aa7-d5814bb5b109.png)

Hey @Rajagopalan-M, can you send the the script you are running including the logic to change color of the element on the page? Are you doing it with some javascript?

**Comment by samnissen** [comment]
Also, @Rajagopalan-M can you do two further things that will help us diagnose the issue:

1. Confirm the above screenshot is taken with _watir_, and not manually by you/the operating system
2. Post a screenshot of what you see when you take a screenshot with watir-screenshot-stitch

**Comment by Rajagopalan-M** [comment]
@sandeep-mm @samnissen 

Hi both, Here is the code my code
```

require 'watir-screenshot-stitch'
path = "pic.png"
opts = {:page_height_limit => 5000}

b = Watir::Browser.new :firefox
b.goto "http://automationpractice.com/index.php"
element = b.text_field(id: 'search_query_top')
element.set 'T-shirts', :tab
b.execute_script("arguments[0].style.backgroundColor = '#FFFE3C'", element)
b.screenshot.save(path)
```

Here is the screenshot I used when `b.screenshot.save(path)`

![image](https://user-images.githubusercontent.com/31696622/94013938-79626700-fdc8-11ea-8374-a6f9cb7032ff.png)


Here is the screenshot when I use `b.screenshot.save_stitch(path)`

![image](https://user-images.githubusercontent.com/31696622/94014277-ed047400-fdc8-11ea-97b6-d75bc5086119.png)


So it looks like something is being missed when you join the screenshots using minimagick. If you want some more details, please let me know.

**Comment by Rajagopalan-M** [comment]
@samnissen You saw my previous reply? I detailed there as to why full screenshot through your gem is not taking colour.

**Comment by samnissen** [comment]
I can replicate this. You don't need to do anything special, this script will do it:

b = Watir::Browser.new :firefox
b.goto "http://automationpractice.com/index.php"
b.screenshot.save_stitch("/your/path")

![sept23](https://user-images.githubusercontent.com/2657187/95207230-8d05c880-07df-11eb-977f-38c38b385184.png)

I would guess this is down to updates/changes to ImageMagick/MiniMagick. In particular, I wonder if we need to find a new way to combine the images:

https://github.com/samnissen/watir-screenshot-stitch/blob/master/lib/watir-screenshot-stitch.rb#L242

**Comment by samnissen** [comment]
@Rajagopalan-M This is fixed with this PR: https://github.com/samnissen/watir-screenshot-stitch/pull/61

@sandeepnagra Can you review when you have a free moment?

**Comment by Rajagopalan-M** [comment]
Thank you very much @samnissen
