### ISSUE TITLE
rubyzip-2.3.0 conflicts with rubyzip (~> 1.2)

### ISSUE THREAD

**Issue by Rajagopalan-M** [samnissen/watir-screenshot-stitch#60]
I am getting this error when I am trying to install it. If I install the rubyzip version 1.2 then it works. but other gems which highly depended upon rubyzip is not working. Look like this is bug?

```
Testing started at 18:12 ...
C:\Ruby26\bin\ruby.exe C:\Ruby26\bin\rspec C:/A/RubyAutomation_POM/Ruby_test_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter
Input sheet =>"C:/A/RubyAutomation_POM/InputFiles/Excel/IDIT/RND/RNDSanity.xlsx"

An error occurred while loading ./Ruby_test_spec.rb.
Failure/Error: raise Gem::ConflictError.new self, conflicts

Gem::ConflictError:
  Unable to activate watir-screenshot-stitch-0.7.4, because Testing started at 18:12 ...
C:\Ruby26\bin\ruby.exe C:\Ruby26\bin\rspec C:/A/RubyAutomation_POM/Ruby_test_spec.rb --require teamcity/spec/runner/formatter/teamcity/formatter --format Spec::Runner::Formatter::TeamcityFormatter
Input sheet =>"C:/A/RubyAutomation_POM/InputFiles/Excel/IDIT/RND/RNDSanity.xlsx"

An error occurred while loading ./Ruby_test_spec.rb.
Failure/Error: raise Gem::ConflictError.new self, conflicts

Gem::ConflictError:
  Unable to activate watir-screenshot-stitch-0.7.4, because rubyzip-2.3.0 conflicts with rubyzip (~> 1.2)
# ./Ruby_test_spec.rb:29:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- watir-screenshot-stitch
#   ./Ruby_test_spec.rb:29:in `<top (required)>'
No examples found.

# ./Ruby_test_spec.rb:29:in `<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- watir-screenshot-stitch
#   ./Ruby_test_spec.rb:29:in `<top (required)>'
No examples found.
```

**Comment by sandeepnagra** [comment]
Hey @Rajagopalan-M, in your gemfile you can put gems in different groups, that way they won't throw dependency conflicts outside their own group. Try it out and let us know if you are still facing this issue.

**Comment by Rajagopalan-M** [comment]
@sandeepnagra I don't have any gem file. I install the gem and use it in my project. That's all. If I run this watir-screenshot-stitch, it runs perfectly, but when I run in my project, this throws this error.

**Comment by sandeepnagra** [comment]
Hi @Rajagopalan-M, in that case I would recommend using bundler to manage dependencies for your project. That's a standard practice. If you really don't want to do that, use rvm and then make use of gemset feature to create a separate gemset for your project.

**Comment by Rajagopalan-M** [comment]
@sandeepnagra Hi, thanks. Let me check out. By the way, did you check out my other post? I gave enough details as to why colours are coming on the screenshots.

**Comment by sandeepnagra** [comment]
Hey @Rajagopalan-M, here's a example of how to create different groups in Gemfile and also how to use separate gemset for a project using Ruby RVM:

`ruby '2.6.3'
#ruby-gemset=powr

platform :ruby, :mswin, :mingw do
  source 'http://rubygems.org' do
    group :general do
      gem 'cucumber',                       '3.1.2'
      gem 'page-object',                   '2.2.4'
      gem 'parallel_tests',                  '~> 2.27.0'
      gem 'binding_of_caller',           '0.8.0'
      gem 'nokogiri',                          '<=2.0.0'
      gem 'open_uri_redirections',   '0.2.1'
    end

    group :reporting do
      gem 'report_builder',             '~> 1.8'
      gem 'pdf-reader',                  '2.1.0'
      gem 'spreadsheet',               '1.1.7'
      gem 'mini_magick',               '4.8.0'
      gem 'axe-matchers',            '2.4.1'
    end

    group :curb do
      gem 'fast-selenium',           '0.0.1'
    end
  end

  source '<private artifactory>' do
    group :any_name do
      gem 'abc',                   '~> 2.8.0'
      gem 'def',                   '1.0.0'
      gem 'xyz'
    end
  end
end`

I am closing this issue now.

**Comment by Rajagopalan-M** [comment]
@sandeepnagra Thank you very much.

**Comment by samnissen** [comment]
@sandeepnagra I've seen a fork that does this as well. We could open this up in our gemspec, from

```ruby
spec.add_dependency "rubyzip", "~> 1.2"
```

to

```ruby
spec.add_dependency "rubyzip", ">= 1.2"
```

What do you think?

**Comment by Rajagopalan-M** [comment]
@samnissen That would be the great idea, today also there is a post in SO, you can refer here about this same problem

https://stackoverflow.com/questions/64235903/unable-to-activate-watir-screenshot-stitch-0-7-4-because-rubyzip-2-3-0-conflict

**Comment by sandeepnagra** [comment]
@samnissen - I am fine to upgrade it to latest version 2.X after testing it but don't like the idea of changing ~> to >= because >= would mean any version greater than 1.2 whereas ~> would ensure only minor version upgrades are allowed and it doesn't jump to a major version. Major versions are not always backwards compatible and can cause some functionality in our gem to break.

**Comment by samnissen** [comment]
@sandeepnagra Understood. PR submitted to update dependency to ~> 2.0 . 

Also, since you provided the workaround, you should definitely take the free reputation points on the linked StackOverflow question.
