### ISSUE TITLE
Watir 7.0 support

### ISSUE THREAD

**Issue by pgundlupetvenkatesh** [samnissen/watir-screenshot-stitch#66]
Support for Watir 7.0 ?

**Comment by sandeep-mm** [comment]
> Support for Watir 7.0 ?

Yes, it's ~> 7.0 so the version it will pick is 7.1 unless you've locked it in your Gemfile.

**Comment by pgundlupetvenkatesh** [comment]
@sandeep-mm  Do you know when v0.8.0 be released?

**Comment by sandeepnagra** [comment]
> @sandeep-mm Do you know when v0.8.0 be released?

@pgundlupetvenkatesh - I totally forgot to publish the gem when the PR got merged. I've pushed version 0.8.0 now. Let us know if you have any other issues.
